apiVersion : apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
        - name: nodebackend 
          image: shopifywebk8registry.azurecr.io/node_backend
          ports:
          - containerPort: 8080
          env:
           - name: COSMOSDB_URL
             valueFrom:
               secretKeyRef:
                 name: cosmodbconnection
                 key: COSMOSDBURL
          resources:
            limits:
              memory: 1000m
            requests:
              memory: 1000m

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 70
